import 'package:flutter/material.dart';

import './src/models/food.dart';

class DataBase {
  static List<Food> foodDB = [
    Food(
      id: 1,
      name: 'Humburger',
      imagePath: 'assets/images/burger.png',
      price: 21,
      rating: 5.0,
      description: 'Delicious Cheesy Humburger',
      recommended: true,
      bgColor: Color(0xFFFFE9C6),
      textColor: Color(0xFFDA9551),
    ),
    Food(
      id: 2,
      name: 'Chips',
      imagePath: 'assets/images/fries.png',
      price: 15,
      rating: 3.5,
      description: 'Crispy frensh fries chips',
      recommended: false,
      bgColor: Color(0xFFC2E3FE),
      textColor: Color(0xFF6A8CAA),
    ),
    Food(
      id: 3,
      name: 'Donuts',
      imagePath: 'assets/images/doughnut.png',
      price: 10,
      rating: 4.0,
      description: 'Sweet Chocolate Donuts',
      recommended: false,
      bgColor: Color(0xFFD7FADA),
      textColor: Color(0xFF56CC7E),
    ),
    Food(
      id: 4,
      name: 'Mexican Taco',
      imagePath: 'assets/images/taco.png',
      price: 18,
      rating: 3.5,
      description: 'Spicy Mexican Taco',
      recommended: true,
      bgColor: Color(0xFFC2E3FE),
      textColor: Color(0xFF6A8CAA),
    ),
    Food(
      id: 5,
      name: 'Hot Dog',
      imagePath: 'assets/images/hotdog.png',
      price: 15,
      rating: 4.0,
      description: 'Super Filled Hot Dog',
      recommended: true,
      bgColor: Color(0xFFFFE9C6),
      textColor: Color(0xFFDA9551),
    ),
    Food(
      id: 6,
      name: 'Pizza',
      imagePath: 'assets/images/pizza.png',
      price: 12,
      rating: 3.0,
      description: 'Traditional margarita pizza',
      recommended: false,
      bgColor: Color(0xFFFFE9C6),
      textColor: Color(0xFFDA9551),
    ),
    Food(
      id: 7,
      name: 'Pop Corn',
      imagePath: 'assets/images/popcorn.png',
      price: 20,
      rating: 4.5,
      description: 'Carmalised pop corn',
      recommended: true,
      bgColor: Color(0xFFD7FADA),
      textColor: Color(0xFF56CC7E),
    ),
  ];
}
